### ISSUE TITLE
Error : events.js:163

### ISSUE THREAD

**Issue by 0xelion** [glambeth/zecProxy#4]
When i've tried to connect a miner on the proxy, it crash with this log :

`miner listener received data{"id":2,"method":"mining.authorize","params":["t1cpWwsC3G3fe1eTJcwr85CdLqqufHn9Qkh.proxy","x"]}
this data has been sent to the mining pool
----------------------------
pool socket has received data{"id":1,"result":true,"error":null}
----------------------------
pool socket has received data{"id":null,"method":"mining.set_target","params":["0020c49ba5e353f7ced916872b020c49ba5e353f7ced916872b020c49ba5e353"]}
sending this to the miners{"id":null,"method":"mining.set_target","params":["0020c49ba5e353f7ced916872b020c49ba5e353f7ced916872b020c49ba5e353"]}
----------------------------
pool socket has received data{"id":null,"method":"mining.notify","params":["d73250a896cd1d5145f8","04000000","4fa6345168ee0f3faf6327fb09f5ccc13f1d1eead857bb29cb2d7a2f00000000","9a1416913fbdaa5625d71f68f9435bd638f72b138a3d78d4d1ad712fe8b1ba66","0000000000000000000000000000000000000000000000000000000000000000","a129e658","8b91001d",true]}
sending this to the miners{"id":null,"method":"mining.notify","params":["d73250a896cd1d5145f8","04000000","4fa6345168ee0f3faf6327fb09f5ccc13f1d1eead857bb29cb2d7a2f00000000","9a1416913fbdaa5625d71f68f9435bd638f72b138a3d78d4d1ad712fe8b1ba66","0000000000000000000000000000000000000000000000000000000000000000","a129e658","8b91001d",true]}
----------------------------

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1034:11)
    at TCP.onread (net.js:580:26)`

**Comment by glambeth** [comment]
Hi, what mining pool are you using? Did your internet disconnect? And are you just connecting one miner to the proxy or multiple?

**Comment by 0xelion** [comment]
I'm mining on Flypool and i'm connecting one miner to the proxy.
