### ISSUE TITLE
Error /root/zecProxy/lib/pool_listener.js:14

### ISSUE THREAD

**Issue by aliceaia** [glambeth/zecProxy#8]
/root/zecProxy/lib/pool_listener.js:14
                console.log(`zecProxy connected to ${config.pool.host}:${config.pool.port}`)
                            ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/zecProxy/proxy.js:1:82)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by hardminercro** [comment]
You have to install npm and node in ubuntu... everything is written in README file!
